# excpected services to be started by upstart/init
# within the regular linux distro of the virtual box
# -> postgresql
# -> redis
# -> xvfb on port :99
celery: python manage.py celeryworker
web: python manage.py runserver --threaded --host=0.0.0.0